import { Buffer } from "node:buffer";
import { diffWordsWithSpace } from "diff";
import {
  DeletedTextRun,
  Document,
  HeadingLevel,
  InsertedTextRun,
  Packer,
  Paragraph,
  TextRun,
  type ParagraphChild,
} from "docx";
import type { AnalysisResult } from "./claudeAnalyzer.js";
import type { Clause } from "./documentParser.js";

interface ExportPayload {
  contractTitle?: string;
  clauses: Clause[];
  analyses: AnalysisResult[];
  author?: string;
}

const normalizeForWord = (text: string) => text.replace(/\s+/g, " ").trim();

const buildRevisionChildren = (
  originalText: string,
  revisedText: string,
  author: string,
  timestamp: string,
  revisionSeed: number,
): ParagraphChild[] => {
  const diff = diffWordsWithSpace(normalizeForWord(originalText), normalizeForWord(revisedText));
  let offset = 0;

  return diff.flatMap((part) => {
    const text = part.value;
    if (!text) return [];

    const id = revisionSeed + offset;
    offset += 1;

    if (part.added) {
      return [
        new InsertedTextRun({
          id,
          author,
          date: timestamp,
          text,
          underline: {},
          color: "1E40AF",
        }),
      ];
    }

    if (part.removed) {
      return [
        new DeletedTextRun({
          id,
          author,
          date: timestamp,
          text,
          strike: true,
          color: "C62828",
        }),
      ];
    }

    return [new TextRun({ text })];
  });
};

export const generateRedlinedDocx = async ({
  contractTitle = "PlaybookRedline Export",
  clauses,
  analyses,
  author = "PlaybookRedline",
}: ExportPayload): Promise<Buffer> => {
  const timestamp = new Date().toISOString();
  const revisionBase = Date.now();
  const analysisMap = new Map(analyses.map((analysis) => [analysis.id, analysis]));

  const children: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [new TextRun(contractTitle)],
    }),
    new Paragraph({
      children: [new TextRun({ text: "Generated by PlaybookRedline", italics: true })],
    }),
  ];

  for (const clause of clauses) {
    const analysis = analysisMap.get(clause.id);
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun(clause.clauseTitle)],
      }),
    );

    if (analysis && analysis.riskLevel !== "green" && analysis.suggestedRedline.trim()) {
      children.push(
        new Paragraph({
          children: buildRevisionChildren(
            clause.originalText,
            analysis.suggestedRedline,
            author,
            timestamp,
            revisionBase + clause.index * 100,
          ),
        }),
      );
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `Issue: ${analysis.issue}`, bold: true }),
            new TextRun({ text: ` | Playbook reference: ${analysis.playbookReference}` }),
          ],
        }),
      );
    } else {
      children.push(
        new Paragraph({
          children: [new TextRun(clause.originalText)],
        }),
      );
    }
  }

  const document = new Document({
    features: { trackRevisions: true },
    sections: [{ children }],
  });

  return Buffer.from(await Packer.toBuffer(document));
};
